// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6aGHFaPDcUvKd_OKl1Y-9l-ujfmDJqR8',
    appId: '1:949036812555:web:e3796059fa1fe44c0bfa0e',
    messagingSenderId: '949036812555',
    projectId: 'note-worthy-f9ed7',
    authDomain: 'note-worthy-f9ed7.firebaseapp.com',
    storageBucket: 'note-worthy-f9ed7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2U4zRIgy4omO1wSEnKLjQnTSNCpJVQgs',
    appId: '1:949036812555:android:82cd28e194550e530bfa0e',
    messagingSenderId: '949036812555',
    projectId: 'note-worthy-f9ed7',
    storageBucket: 'note-worthy-f9ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QWCXtRnlQxCiapVIdzLUm8UWPSOczKI',
    appId: '1:949036812555:ios:679cbe8e17dfa3750bfa0e',
    messagingSenderId: '949036812555',
    projectId: 'note-worthy-f9ed7',
    storageBucket: 'note-worthy-f9ed7.appspot.com',
    iosBundleId: 'com.example.noteWorthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1QWCXtRnlQxCiapVIdzLUm8UWPSOczKI',
    appId: '1:949036812555:ios:d2bb66c4895c2a300bfa0e',
    messagingSenderId: '949036812555',
    projectId: 'note-worthy-f9ed7',
    storageBucket: 'note-worthy-f9ed7.appspot.com',
    iosBundleId: 'com.example.noteWorthy.RunnerTests',
  );
}
